workflows:
  android-ios-build:
    name: Farm App - APK + IPA Release
    instance_type: mac_mini_m1  # 클라우드 맥 (무료)
    max_build_duration: 60  # 안전 60분
    environment:
      flutter: stable  # Flutter 버전 (Dart 포함)
    triggering:
      events:
        - push  # 푸시 시 자동
      branch_patterns:
        - pattern: main
    scripts:
      - name: Get packages
        script: |
          flutter pub get
      - name: Build Android APK (Release)
        script: |
          flutter build apk --release  # 디버그 → 릴리즈 변경
      - name: Build iOS IPA (Release)
        script: |
          flutter build ipa --release --no-codesign  # ZIP → IPA
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk  # APK 경로
      - build/ios/ipa/*.ipa  # IPA 경로
    publishing:
      email:
        recipients:
          - beat4030@gmail.com  # 당신 이메일 (완료 알림)