// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF39OOaOqrf-DgRsD2fjOgZbHSHPO_mbM',
    appId: '1:491565800299:android:704ab335fc2df8f00f4a2e',
    messagingSenderId: '491565800299',
    projectId: 'thai-koreashop',
    storageBucket: 'thai-koreashop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK2qI2EN8QM3oRp6ctXN5V4s4nFOOoP2A',
    appId: '1:491565800299:ios:adbcc60d70c684e20f4a2e',
    messagingSenderId: '491565800299',
    projectId: 'thai-koreashop',
    storageBucket: 'thai-koreashop.firebasestorage.app',
    iosBundleId: 'com.example.thaiKoreaShop',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8NChzoPKwXUH2uWvVB9-uO30l3ZX5R6s',
    appId: '1:491565800299:web:a04de231dd19add40f4a2e',
    messagingSenderId: '491565800299',
    projectId: 'thai-koreashop',
    authDomain: 'thai-koreashop.firebaseapp.com',
    storageBucket: 'thai-koreashop.firebasestorage.app',
    measurementId: 'G-XB80B55RHD',
  );

}